export { default as Home } from './Home';
export { default as NotFound } from './NotFound';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as BusinessIntelligence } from './dashboards/BusinessIntelligence';
export { default as InventoryAndStock } from './dashboards/InventoryAndStock';
export { default as OperationalPerformance } from './dashboards/OperationalPerformance';
export { default as OrdersAndShipping } from './dashboards/OrdersAndShipping';
export { default as SafetyAndMaintenance } from './dashboards/SafetyAndMaintenance';
